export const incomeStatementColumns = [
  { field: 'fiscalDateEnding', headerName: 'Fiscal Date Ending', width: 180 },
  { field: 'reportedCurrency', headerName: 'Reported Currency', width: 180 },
  { field: 'grossProfit', headerName: 'Gross Profit', width: 180 },
  { field: 'totalRevenue', headerName: 'Total Revenue', width: 180 },
  { field: 'costOfRevenue', headerName: 'Cost of Revenue', width: 180 },
  { field: 'costofGoodsAndServicesSold', headerName: 'Cost of Goods and Services Sold', width: 180 },
  { field: 'operatingIncome', headerName: 'Operating Income', width: 180 },
  { field: 'sellingGeneralAndAdministrative', headerName: 'Selling, General and Administrative', width: 180 },
  { field: 'researchAndDevelopment', headerName: 'Research and Development', width: 180 },
  { field: 'operatingExpenses', headerName: 'Operating Expenses', width: 180 },
  { field: 'investmentIncomeNet', headerName: 'Investment Income Net', width: 180 },
  { field: 'netInterestIncome', headerName: 'Net Interest Income', width: 180 },
  { field: 'interestIncome', headerName: 'Interest Income', width: 180 },
  { field: 'interestExpense', headerName: 'Interest Expense', width: 180 },
  { field: 'nonInterestIncome', headerName: 'Non-Interest Income', width: 180 },
  { field: 'otherNonOperatingIncome', headerName: 'Other Non-Operating Income', width: 180 },
  { field: 'depreciation', headerName: 'Depreciation', width: 180 },
  { field: 'depreciationAndAmortization', headerName: 'Depreciation and Amortization', width: 180 },
  { field: 'incomeBeforeTax', headerName: 'Income Before Tax', width: 180 },
  { field: 'incomeTaxExpense', headerName: 'Income Tax Expense', width: 180 },
  { field: 'interestAndDebtExpense', headerName: 'Interest and Debt Expense', width: 180 },
  { field: 'netIncomeFromContinuingOperations', headerName: 'Net Income from Continuing Operations', width: 180 },
  { field: 'comprehensiveIncomeNetOfTax', headerName: 'Comprehensive Income Net of Tax', width: 180 },
  { field: 'ebit', headerName: 'EBIT', width: 180 },
  { field: 'ebitda', headerName: 'EBITDA', width: 180 },
  { field: 'netIncome', headerName: 'Net Income', width: 180 }
];

export const balanceSheetColumns = [
  { field: 'fiscalDateEnding', headerName: 'Fiscal Date Ending', width: 180 },
  { field: 'reportedCurrency', headerName: 'Reported Currency', width: 180 },
  { field: 'totalAssets', headerName: 'Total Assets', width: 180 },
  { field: 'totalCurrentAssets', headerName: 'Total Current Assets', width: 180 },
  { field: 'cashAndCashEquivalentsAtCarryingValue', headerName: 'Cash and Cash Equivalents', width: 180 },
  { field: 'cashAndShortTermInvestments', headerName: 'Cash and Short-Term Investments', width: 180 },
  { field: 'inventory', headerName: 'Inventory', width: 180 },
  { field: 'currentNetReceivables', headerName: 'Current Net Receivables', width: 180 },
  { field: 'totalNonCurrentAssets', headerName: 'Total Non-Current Assets', width: 180 },
  { field: 'propertyPlantEquipment', headerName: 'Property, Plant, Equipment', width: 180 },
  { field: 'accumulatedDepreciationAmortizationPPE', headerName: 'Accumulated Depreciation/Amortization (PPE)', width: 180 },
  { field: 'intangibleAssets', headerName: 'Intangible Assets', width: 180 },
  { field: 'intangibleAssetsExcludingGoodwill', headerName: 'Intangible Assets (Excl. Goodwill)', width: 180 },
  { field: 'goodwill', headerName: 'Goodwill', width: 180 },
  { field: 'investments', headerName: 'Investments', width: 180 },
  { field: 'longTermInvestments', headerName: 'Long-Term Investments', width: 180 },
  { field: 'shortTermInvestments', headerName: 'Short-Term Investments', width: 180 },
  { field: 'otherCurrentAssets', headerName: 'Other Current Assets', width: 180 },
  { field: 'otherNonCurrentAssets', headerName: 'Other Non-Current Assets', width: 180 },
  { field: 'totalLiabilities', headerName: 'Total Liabilities', width: 180 },
  { field: 'totalCurrentLiabilities', headerName: 'Total Current Liabilities', width: 180 },
  { field: 'currentAccountsPayable', headerName: 'Current Accounts Payable', width: 180 },
  { field: 'deferredRevenue', headerName: 'Deferred Revenue', width: 180 },
  { field: 'currentDebt', headerName: 'Current Debt', width: 180 },
  { field: 'shortTermDebt', headerName: 'Short-Term Debt', width: 180 },
  { field: 'totalNonCurrentLiabilities', headerName: 'Total Non-Current Liabilities', width: 180 },
  { field: 'capitalLeaseObligations', headerName: 'Capital Lease Obligations', width: 180 },
  { field: 'longTermDebt', headerName: 'Long-Term Debt', width: 180 },
  { field: 'currentLongTermDebt', headerName: 'Current Long-Term Debt', width: 180 },
  { field: 'longTermDebtNoncurrent', headerName: 'Long-Term Debt (Non-Current)', width: 180 },
  { field: 'shortLongTermDebtTotal', headerName: 'Short/Long-Term Debt Total', width: 180 },
  { field: 'otherCurrentLiabilities', headerName: 'Other Current Liabilities', width: 180 },
  { field: 'otherNonCurrentLiabilities', headerName: 'Other Non-Current Liabilities', width: 180 },
  { field: 'totalShareholderEquity', headerName: 'Total Shareholder Equity', width: 180 },
  { field: 'treasuryStock', headerName: 'Treasury Stock', width: 180 },
  { field: 'retainedEarnings', headerName: 'Retained Earnings', width: 180 },
  { field: 'commonStock', headerName: 'Common Stock', width: 180 },
  { field: 'commonStockSharesOutstanding', headerName: 'Common Stock Shares Outstanding', width: 180 }
];

